### ISSUE TITLE
add trackwall surface

### ISSUE THREAD

**Issue by ezio416** [racacax/openplanet_better_texture_mod#1]
Since this plugin is geared towards visibility, and TrackWall (which for some reason I thought was called fabric) is black and often hard to see, it would be nice to make it lighter. ~~Officially the physics material is called `ResonantMetal` but I'm not sure that helps~~

**Comment by racacax** [comment]
I'll look into that ! From what I understand, the texture files are TrackWallClips_D.dds and TrackWall_D.dds. We'll see what kind of presets I can provide

**Comment by racacax** [comment]
![Image](https://github.com/racacax/openplanet_better_texture_mod/assets/9437635/d4c09574-ad86-4ef6-95c2-66056f3243e4)

Working on the next update, this is the idea I got. Considering it's the same behaviour as PlatformTech, it's not a big deal if I make it grey. It can help differenciate from Black Plastic and magnet more

**Comment by ezio416** [comment]
That looks great! I actually hadn't considered the border but that's a nice touch and would help a lot, thank you!

**Comment by racacax** [comment]
Surface added in version 1.0.0
