### ISSUE TITLE
"Ask me everytime" shows after leaving map

### ISSUE THREAD

**Issue by ezio416** [racacax/openplanet_better_texture_mod#13]
I joined a map with a mod, got the pop-up, left the map without making a selection, and the pop-up is still there

<img width="611" alt="Screenshot 2024-02-08 135506" src="https://github.com/racacax/openplanet_better_texture_mod/assets/37951898/c2f4a7fe-e65c-4610-a149-82c268d33f7a">

**Comment by racacax** [comment]
Indeed, ty for telling me. This will be an easy fix, I'll do it ASAP

**Comment by racacax** [comment]
Fixed. Added in version 1.1.1
